services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "4242:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
